server:
  port: 8095
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: 'http://localhost:9111/eureka/'
  instance:
    preferIpAddress: true
spring:
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

